/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './mention-list.component';
const styles_MentionListComponent:any[] = ([] as any[]);
export const RenderType_MentionListComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_MentionListComponent,data:{}});
function View_MentionListComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(0,(null as any),['\n      ','\n    ']))],(null as any),
      (_ck,_v) => {
        var _co:any = _v.component;
        const currVal_0:any = _v.context.item[_co.labelKey];
        _ck(_v,0,0,currVal_0);
      });
}
function View_MentionListComponent_3(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵand(0,(null as any),(null as any),0))],(null as any),
      (null as any));
}
function View_MentionListComponent_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),8,'li',([] as any[]),
      [[2,'active',(null as any)]],(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n            '])),(_l()(),i0.ɵeld(2,0,(null as any),
          (null as any),5,'a',[['class','dropdown-item']],(null as any),[[(null as any),
              'mousedown']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:any = _v.component;
            if (('mousedown' === en)) {
              _co.activeIndex = _v.context.index;
              _co.itemClick.emit();
              const pd_0:any = ((<any>$event.preventDefault()) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n              '])),
      (_l()(),i0.ɵand(16777216,(null as any),(null as any),2,(null as any),View_MentionListComponent_3)),
      i0.ɵdid(5,540672,(null as any),0,i1.NgTemplateOutlet,[i0.ViewContainerRef],{ngTemplateOutletContext:[0,
          'ngTemplateOutletContext'],ngTemplateOutlet:[1,'ngTemplateOutlet']},(null as any)),
      i0.ɵpod(6,{'item':0}),(_l()(),i0.ɵted(-1,(null as any),['\n            '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n        ']))],(_ck,_v) => {
    var _co:any = _v.component;
    const currVal_1:any = _ck(_v,6,0,_v.context.$implicit);
    const currVal_2:any = _co.itemTemplate;
    _ck(_v,5,0,currVal_1,currVal_2);
  },(_ck,_v) => {
    var _co:any = _v.component;
    const currVal_0:any = (_co.activeIndex == _v.context.index);
    _ck(_v,0,0,currVal_0);
  });
}
export function View_MentionListComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{list:0}),i0.ɵqud(402653184,2,{defaultItemTemplate:0}),
      (_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵand(0,[[2,2],['defaultItemTemplate',
          2]],(null as any),0,(null as any),View_MentionListComponent_1)),(_l()(),
          i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(5,0,[[1,0],['list',
          1]],(null as any),4,'ul',[['class','dropdown-menu scrollable-menu']],[[8,
          'hidden',0]],(null as any),(null as any),(null as any),(null as any))),(_l()(),
          i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_MentionListComponent_2)),i0.ɵdid(8,802816,
          (null as any),0,i1.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],
          {ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted(-1,(null as any),
          ['\n    '])),(_l()(),i0.ɵted(-1,(null as any),['\n    ']))],(_ck,_v) => {
    var _co:i2.MentionListComponent = _v.component;
    const currVal_1:any = _co.items;
    _ck(_v,8,0,currVal_1);
  },(_ck,_v) => {
    var _co:i2.MentionListComponent = _v.component;
    const currVal_0:any = _co.hidden;
    _ck(_v,5,0,currVal_0);
  });
}
export function View_MentionListComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'mention-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_MentionListComponent_0,
      RenderType_MentionListComponent)),i0.ɵdid(1,114688,(null as any),0,i2.MentionListComponent,
      [i0.ElementRef],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MentionListComponentNgFactory:i0.ComponentFactory<i2.MentionListComponent> = i0.ɵccf('mention-list',
    i2.MentionListComponent,View_MentionListComponent_Host_0,{labelKey:'labelKey',
        itemTemplate:'itemTemplate'},{itemClick:'itemClick'},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2dsaW0vYW5ndWxhci1tZW50aW9ucy9tZW50aW9uL21lbnRpb24tbGlzdC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvZ2xpbS9hbmd1bGFyLW1lbnRpb25zL21lbnRpb24vbWVudGlvbi1saXN0LmNvbXBvbmVudC5kLnRzIiwibmc6Ly8vVXNlcnMvZ2xpbS9hbmd1bGFyLW1lbnRpb25zL21lbnRpb24vbWVudGlvbi1saXN0LmNvbXBvbmVudC5kLnRzLk1lbnRpb25MaXN0Q29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9nbGltL2FuZ3VsYXItbWVudGlvbnMvbWVudGlvbi9tZW50aW9uLWxpc3QuY29tcG9uZW50LmQudHMuTWVudGlvbkxpc3RDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8bmctdGVtcGxhdGUgI2RlZmF1bHRJdGVtVGVtcGxhdGUgbGV0LWl0ZW09XCJpdGVtXCI+XG4gICAgICB7e2l0ZW1bbGFiZWxLZXldfX1cbiAgICA8L25nLXRlbXBsYXRlPlxuICAgIDx1bCAjbGlzdCBbaGlkZGVuXT1cImhpZGRlblwiIGNsYXNzPVwiZHJvcGRvd24tbWVudSBzY3JvbGxhYmxlLW1lbnVcIj5cbiAgICAgICAgPGxpICpuZ0Zvcj1cImxldCBpdGVtIG9mIGl0ZW1zOyBsZXQgaSA9IGluZGV4XCIgW2NsYXNzLmFjdGl2ZV09XCJhY3RpdmVJbmRleD09aVwiPlxuICAgICAgICAgICAgPGEgY2xhc3M9XCJkcm9wZG93bi1pdGVtXCIgKG1vdXNlZG93bik9XCJhY3RpdmVJbmRleD1pO2l0ZW1DbGljay5lbWl0KCk7JGV2ZW50LnByZXZlbnREZWZhdWx0KClcIj5cbiAgICAgICAgICAgICAgPG5nLXRlbXBsYXRlIFtuZ1RlbXBsYXRlT3V0bGV0XT1cIml0ZW1UZW1wbGF0ZVwiIFtuZ1RlbXBsYXRlT3V0bGV0Q29udGV4dF09XCJ7J2l0ZW0nOml0ZW19XCI+PC9uZy10ZW1wbGF0ZT5cbiAgICAgICAgICAgIDwvYT5cbiAgICAgICAgPC9saT5cbiAgICA8L3VsPlxuICAgICIsIjxtZW50aW9uLWxpc3Q+PC9tZW50aW9uLWxpc3Q+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0NzRDs7O1FBQUE7UUFBQTs7Ozs7Ozs7b0JBSTlDO01BQUE7TUFBOEUsc0RBQzFFO1VBQUE7Y0FBQTtZQUFBO1lBQUE7WUFBeUI7Y0FBQTtjQUFBO2NBQUE7Y0FBQTtZQUFBO1lBQXpCO1VBQUEsZ0NBQThGO01BQzVGO2FBQUE7VUFBQTthQUErQyxlQUF3RDtNQUNyRzs7SUFENkM7SUFBbEM7SUFBYixXQUErQyxVQUFsQyxTQUFiOzs7SUFGd0M7SUFBOUMsV0FBOEMsU0FBOUM7Ozs7O01BTFIsOENBQ0k7VUFBQSxnRUFFYztpQkFBQSwrQkFDZDtVQUFBO1VBQUEsdUVBQWtFO2lCQUFBLG1DQUM5RDtVQUFBLG1FQUFBO1VBQUE7VUFBQSx1Q0FJSztVQUFBLGFBQ0o7O0lBTEc7SUFBSixXQUFJLFNBQUo7OztJQURNO0lBQVYsV0FBVSxTQUFWOzs7O29CQ0pKO01BQUE7cUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7OyJ9
